In [2]:
"""
缺失值处理主要方法：
1：丢弃
2：补全
3：真值转换
4：忽略

sklearn中有impute方法对缺失值进行处理
或直接pandas中用fillna()函数
"""

'\n缺失值处理主要方法：\n1：丢弃\n2：补全\n3：真值转换\n4：忽略\n\nsklearn中有impute方法对缺失值进行处理\n或直接pandas中用fillna()函数\n'

In [3]:
import pandas as pd
import numpy as np

'''
创建一个有nan值的dataframe
'''
df = pd.DataFrame(np.random.randn(6,4),columns = ['col1','col2','col3','col4'])
df.iloc[1:2,1] = np.nan
df.iloc[4,3] = np.nan
print(df)

nan_all = df.isnull()
print(nan_all)

       col1      col2      col3      col4
0  0.415629 -0.183139 -0.146892  0.523108
1 -0.998354       NaN -0.932243  0.140786
2  1.312101 -2.083496  0.906759  0.490925
3 -1.579474  0.449776 -1.208180  1.075324
4 -1.669224  0.016726 -0.180254       NaN
5 -1.401127 -1.692252  0.326683  1.080635
    col1   col2   col3   col4
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False  False


In [4]:
'''
获得有nan的列和全部为nan的列
'''
nan_col1 = df.isnull().any()
nan_col2 = df.isnull().all()
print(nan_col1)
print(nan_col2)

col1    False
col2     True
col3    False
col4     True
dtype: bool
col1    False
col2    False
col3    False
col4    False
dtype: bool


In [5]:
'''丢弃缺失值'''
df2 = df.dropna()
print(df2)

       col1      col2      col3      col4
0  0.415629 -0.183139 -0.146892  0.523108
2  1.312101 -2.083496  0.906759  0.490925
3 -1.579474  0.449776 -1.208180  1.075324
5 -1.401127 -1.692252  0.326683  1.080635


In [6]:
#使用sklearn的simpleImputer将缺失值替换为指定值
from sklearn.impute import SimpleImputer
nan_model = SimpleImputer(missing_values=np.nan,strategy= 'mean')
nan_result = nan_model.fit_transform(df)
print(nan_result)

[[ 0.41562862 -0.18313901 -0.14689151  0.52310828]
 [-0.9983536  -0.69847706 -0.93224348  0.14078634]
 [ 1.31210077 -2.08349593  0.90675916  0.4909251 ]
 [-1.57947367  0.44977559 -1.20818012  1.07532447]
 [-1.66922387  0.01672623 -0.18025367  0.66215577]
 [-1.40112698 -1.69225218  0.32668339  1.08063466]]


In [9]:
#使用pandas替换缺失值
nan_result_pd1 = df.fillna(0)
print("fill nan with 0\n",nan_result_pd1,'\n')
nan_result_pd2 = df.fillna(method = 'backfill',axis = 0)
print("fill nan with the next valid value\n",nan_result_pd2,'\n')
nan_result_pd3 = df.fillna(method = 'pad')
print("fill nan with the previous valid value\n", nan_result_pd3,'\n')
nan_result_pd4 = df.fillna({'col2':888,'col4':999})
print("fill specific nan with specific value\n",nan_result_pd4,'\n')
print(df.mean()['col1':'col4'])
nan_result_pd5 = df.fillna(df.mean()['col1':'col4'])
print("fill na with mean\n",nan_result_pd5,'\n')

fill nan with 0
        col1      col2      col3      col4
0  0.415629 -0.183139 -0.146892  0.523108
1 -0.998354  0.000000 -0.932243  0.140786
2  1.312101 -2.083496  0.906759  0.490925
3 -1.579474  0.449776 -1.208180  1.075324
4 -1.669224  0.016726 -0.180254  0.000000
5 -1.401127 -1.692252  0.326683  1.080635 

fill nan with the next valid value
        col1      col2      col3      col4
0  0.415629 -0.183139 -0.146892  0.523108
1 -0.998354 -2.083496 -0.932243  0.140786
2  1.312101 -2.083496  0.906759  0.490925
3 -1.579474  0.449776 -1.208180  1.075324
4 -1.669224  0.016726 -0.180254  1.080635
5 -1.401127 -1.692252  0.326683  1.080635 

fill nan with the previous valid value
        col1      col2      col3      col4
0  0.415629 -0.183139 -0.146892  0.523108
1 -0.998354 -0.183139 -0.932243  0.140786
2  1.312101 -2.083496  0.906759  0.490925
3 -1.579474  0.449776 -1.208180  1.075324
4 -1.669224  0.016726 -0.180254  1.075324
5 -1.401127 -1.692252  0.326683  1.080635 

fill specific nan w